//! Protobuf serialization and deserialization through zero-sized typed schemas.
//!
//! Instead of generating structs to hold your data (like prost), tacky generates a schema you
//! write your existing data through, in whatever form it's already in.
//!
//! The runtime library provides:
//! - [`Field`], the main schema type, generic over field number and protobuf type
//! - [Scalar markers](`scalars`), zero-sized types like [`Int32`] and [`PbString`] that carry
//!   wire format information
//! - [Field labels](`field`): [`Optional`], [`Repeated`], [`Packed`], [`Required`], [`Plain`],
//!   [`PbMap`]
//! - [`Tack`], the backtracking length primitive that enables single-pass serialization
//! - [Buffers](`buf`): `Vec<u8>` and [`SliceBuf`] for no-alloc
//!
//! Schema structs and field enums are generated by `tacky-build` at build time.
//!
//! # Panics
//!
//! Encoding panics where a conventional API would return `Err`. Decoding never does, so nothing
//! a peer sends can panic. Every encode panic is a function of the message and the buffer, never
//! of an allocator, a clock or a thread, so it reproduces on every run.
//!
//! Most are caller bugs. A bad placeholder width, a [`PbWrite`] closure or [`PbDisplay`] value
//! that fails mid-field. The one a correct program can reach is a fixed buffer running out of
//! room (`SliceBuf overflow`). There are three ways to handle that.
//!
//! - Stop at a record boundary. Compare [`SliceBuf::written`]'s length against the capacity you
//!   handed over and skip a record whose worst case does not fit. This is the only point at which
//!   a partial result is well-formed, and the only option under `panic = "abort"`.
//! - Encode into a `Vec<u8>`, which grows.
//! - Use `catch_unwind` for "this record does not fit, flush and retry", which needs
//!   `panic = "unwind"` and the `std` feature. Wrap the closure in `AssertUnwindSafe` and
//!   discard the whole buffer on `Err`, since an interrupted record may already have a plausible
//!   length patched over a truncated payload. Salvaging the records that already fitted needs
//!   the boundary length above.
//!
//! Two checks are `debug_assert!` because release cannot afford them. `write_exact` compares
//! `ExactSizeIterator::len()` against the bytes written, and a map entry checks its predicted
//! size. Both catch a caller contract slip that corrupts the message rather than breaking safety.

#![no_std]
#![allow(clippy::new_without_default)]

#[cfg(feature = "alloc")]
extern crate alloc;

#[cfg(feature = "std")]
extern crate std;

pub mod buf;
pub mod field;
pub mod scalars;
pub mod tack;
pub use buf::*;
pub use field::*;
pub use scalars::*;
pub use tack::*;
