//! Protobuf serialization and deserialization through zero-sized typed schemas.
//!
//! Instead of generating structs to hold your data (like prost), tacky generates
//! a schema you write your existing data through — in whatever form it's already in.
//!
//! The runtime library provides:
//! - [`Field`] — the main schema type, generic over field number and protobuf type
//! - [Scalar markers](`scalars`) — zero-sized types like [`Int32`], [`PbString`] that carry wire format information
//! - [Field labels](`field`) — [`Optional`], [`Repeated`], [`Packed`], [`Required`], [`Plain`], [`PbMap`]
//! - [`Tack`] — the backtracking length primitive that enables single-pass serialization
//!
//! Schema structs and field enums are generated by `tacky-build` at build time.

#![no_std]
#![allow(clippy::new_without_default)]

#[cfg(feature = "alloc")]
extern crate alloc;

pub mod buf;
pub mod field;
pub mod scalars;
pub mod tack;
pub use buf::*;
pub use field::*;
pub use scalars::*;
pub use tack::*;
